export class Atleta{
    idAtleta!:number;
    nomeSocieta!:string;
    codiceTessera!:string;
    nome!:string;
    cognome!:string;
    sesso!:string;
    cF!:string;
    dataNascita!:string;
    IDComuneNascita!:string;
    IDComuneResidenza!:string;
    indirizzo!:string;
    cap!:string;
    email!:string;
    tel!:string;
    altezza!:string;
    peso!:string;
    dataScadenzaCertificato!:string;
    puntiBase!:string;
    nascondi!:string;
    URL_Foto!:string;
    URL_CertificatoMedico!:string;
}